#server:
#  port: 8083
#spring:
#  application:
#    name: Leave
#  datasource:
#    url: jdbc:postgresql://localhost:5432/LeaveApplication
#    username: postgres
#    password: 123
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#eureka:
#  instance:
#    prefer-ip-address:true
#  client:
#    fetch-registry:true
#    register-with-eureka:true
#  server-url:
#    defaultZone: http://localhost:8761/eureka
server:
  port: 8083

spring:
  application:
    name: Leave
  datasource:
    url: jdbc:postgresql://localhost:5432/LeaveApplication
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
